---
languageCode: es
languageName: ES
params:
  DateFormat: January 02, 2006
  profileMode:
    enabled: true
    imageUrl: "/home.png"
    imageTitle: "cabecera"
    subtitle: Hago m√∫sica
    buttons:
      - identifier: portfolio
        name: Mis Trabajos
        url: "/portfolio"
weight: 1